"""Business categories useful for IT services lead generation."""

IT_LEAD_CATEGORIES = [
    {
        "id": "all_businesses",
        "label": "All Businesses",
        "query": "businesses",
        "place_type": None,
        "description": "Broad search — offices, shops, clinics, and more",
    },
    {
        "id": "offices",
        "label": "Offices & Corporate",
        "query": "corporate office",
        "place_type": "corporate_office",
        "description": "Companies needing managed IT, cloud, and support",
    },
    {
        "id": "startups",
        "label": "Startups & Coworking",
        "query": "coworking space startup",
        "place_type": "coworking_space",
        "description": "Fast-growing teams needing infrastructure setup",
    },
    {
        "id": "healthcare",
        "label": "Hospitals & Clinics",
        "query": "hospital clinic",
        "place_type": "hospital",
        "description": "Healthcare — EMR, networking, compliance IT",
    },
    {
        "id": "dental",
        "label": "Dental & Medical Practices",
        "query": "dental clinic doctor",
        "place_type": "dentist",
        "description": "Small practices needing IT support & backups",
    },
    {
        "id": "schools",
        "label": "Schools & Colleges",
        "query": "school college university",
        "place_type": "school",
        "description": "Education — labs, Wi-Fi, admin systems",
    },
    {
        "id": "retail",
        "label": "Retail & Shops",
        "query": "retail store shop",
        "place_type": "store",
        "description": "POS, inventory, and network setup",
    },
    {
        "id": "restaurants",
        "label": "Restaurants & Cafes",
        "query": "restaurant cafe",
        "place_type": "restaurant",
        "description": "Billing systems, Wi-Fi, and POS support",
    },
    {
        "id": "hotels",
        "label": "Hotels & Hospitality",
        "query": "hotel resort",
        "place_type": "lodging",
        "description": "Property management & guest Wi-Fi",
    },
    {
        "id": "real_estate",
        "label": "Real Estate",
        "query": "real estate agency",
        "place_type": "real_estate_agency",
        "description": "CRM, listings, and office IT",
    },
    {
        "id": "law_firms",
        "label": "Law Firms",
        "query": "law firm advocate",
        "place_type": "lawyer",
        "description": "Document management & secure networks",
    },
    {
        "id": "accounting",
        "label": "CA & Accounting Firms",
        "query": "chartered accountant CA firm",
        "place_type": "accounting",
        "description": "Tax software, backups, and security",
    },
    {
        "id": "banks_finance",
        "label": "Banks & Finance",
        "query": "bank finance company",
        "place_type": "bank",
        "description": "Branch IT and security infrastructure",
    },
    {
        "id": "manufacturing",
        "label": "Manufacturing & Industrial",
        "query": "factory manufacturing industrial",
        "place_type": None,
        "description": "ERP, IoT, and plant network systems",
    },
    {
        "id": "gyms",
        "label": "Gyms & Fitness",
        "query": "gym fitness center",
        "place_type": "gym",
        "description": "Membership systems and AV setup",
    },
    {
        "id": "salons",
        "label": "Salons & Spas",
        "query": "salon spa beauty",
        "place_type": "beauty_salon",
        "description": "Booking software and POS",
    },
    {
        "id": "auto_dealers",
        "label": "Auto Dealers & Showrooms",
        "query": "car dealer showroom",
        "place_type": "car_dealer",
        "description": "DMS, CCTV, and network infrastructure",
    },
    {
        "id": "warehouses",
        "label": "Warehouses & Logistics",
        "query": "warehouse logistics",
        "place_type": None,
        "description": "Inventory systems and barcode IT",
    },
    {
        "id": "construction",
        "label": "Construction Companies",
        "query": "construction builder contractor",
        "place_type": None,
        "description": "Site offices and project management IT",
    },
    {
        "id": "custom",
        "label": "Custom Search",
        "query": "",
        "place_type": None,
        "description": "Enter your own business type or keyword",
    },
]

INDIAN_CITIES = [
    "Ahmedabad, Gujarat",
    "Mumbai, Maharashtra",
    "Delhi, India",
    "Bangalore, Karnataka",
    "Hyderabad, Telangana",
    "Chennai, Tamil Nadu",
    "Pune, Maharashtra",
    "Kolkata, West Bengal",
    "Surat, Gujarat",
    "Jaipur, Rajasthan",
    "Lucknow, Uttar Pradesh",
    "Chandigarh, India",
    "Indore, Madhya Pradesh",
    "Nagpur, Maharashtra",
    "Vadodara, Gujarat",
    "Rajkot, Gujarat",
    "Bhopal, Madhya Pradesh",
    "Coimbatore, Tamil Nadu",
    "Kochi, Kerala",
    "Goa, India",
]

COUNTRIES = [
    {"code": "IN", "name": "India"},
    {"code": "US", "name": "United States"},
    {"code": "GB", "name": "United Kingdom"},
    {"code": "AE", "name": "United Arab Emirates"},
    {"code": "CA", "name": "Canada"},
    {"code": "AU", "name": "Australia"},
    {"code": "SG", "name": "Singapore"},
    {"code": "DE", "name": "Germany"},
]
