"""Worldwide location data — all countries and preset cities by region."""

REGIONS = [
    {"id": "worldwide", "label": "Popular Worldwide"},
    {"id": "asia", "label": "Asia"},
    {"id": "europe", "label": "Europe"},
    {"id": "americas", "label": "Americas"},
    {"id": "mea", "label": "Middle East & Africa"},
    {"id": "oceania", "label": "Oceania"},
]

PRESET_LOCATIONS: dict[str, list[str]] = {
    "worldwide": [
        "New York, NY, USA",
        "London, UK",
        "Dubai, UAE",
        "Singapore",
        "Sydney, Australia",
        "Toronto, Canada",
        "Berlin, Germany",
        "Paris, France",
        "Tokyo, Japan",
        "Mumbai, India",
    ],
    "asia": [
        "Mumbai, Maharashtra, India",
        "Delhi, India",
        "Bangalore, Karnataka, India",
        "Hyderabad, Telangana, India",
        "Chennai, Tamil Nadu, India",
        "Ahmedabad, Gujarat, India",
        "Pune, Maharashtra, India",
        "Kolkata, West Bengal, India",
        "Surat, Gujarat, India",
        "Jaipur, Rajasthan, India",
        "Lucknow, Uttar Pradesh, India",
        "Chandigarh, India",
        "Indore, Madhya Pradesh, India",
        "Kochi, Kerala, India",
        "Tokyo, Japan",
        "Osaka, Japan",
        "Seoul, South Korea",
        "Bangkok, Thailand",
        "Jakarta, Indonesia",
        "Kuala Lumpur, Malaysia",
        "Manila, Philippines",
        "Ho Chi Minh City, Vietnam",
        "Hong Kong",
        "Shanghai, China",
        "Beijing, China",
        "Taipei, Taiwan",
        "Karachi, Pakistan",
        "Lahore, Pakistan",
        "Dhaka, Bangladesh",
        "Colombo, Sri Lanka",
        "Kathmandu, Nepal",
    ],
    "europe": [
        "London, UK",
        "Manchester, UK",
        "Birmingham, UK",
        "Paris, France",
        "Berlin, Germany",
        "Munich, Germany",
        "Frankfurt, Germany",
        "Amsterdam, Netherlands",
        "Brussels, Belgium",
        "Madrid, Spain",
        "Barcelona, Spain",
        "Rome, Italy",
        "Milan, Italy",
        "Zurich, Switzerland",
        "Vienna, Austria",
        "Warsaw, Poland",
        "Prague, Czech Republic",
        "Stockholm, Sweden",
        "Oslo, Norway",
        "Copenhagen, Denmark",
        "Dublin, Ireland",
        "Lisbon, Portugal",
        "Athens, Greece",
        "Bucharest, Romania",
        "Istanbul, Turkey",
        "Moscow, Russia",
        "Kyiv, Ukraine",
    ],
    "americas": [
        "New York, NY, USA",
        "Los Angeles, CA, USA",
        "Chicago, IL, USA",
        "Houston, TX, USA",
        "San Francisco, CA, USA",
        "Miami, FL, USA",
        "Seattle, WA, USA",
        "Boston, MA, USA",
        "Dallas, TX, USA",
        "Atlanta, GA, USA",
        "Toronto, Canada",
        "Vancouver, Canada",
        "Montreal, Canada",
        "Mexico City, Mexico",
        "São Paulo, Brazil",
        "Rio de Janeiro, Brazil",
        "Buenos Aires, Argentina",
        "Santiago, Chile",
        "Bogotá, Colombia",
        "Lima, Peru",
    ],
    "mea": [
        "Dubai, UAE",
        "Abu Dhabi, UAE",
        "Riyadh, Saudi Arabia",
        "Jeddah, Saudi Arabia",
        "Doha, Qatar",
        "Kuwait City, Kuwait",
        "Manama, Bahrain",
        "Muscat, Oman",
        "Tel Aviv, Israel",
        "Jerusalem, Israel",
        "Cairo, Egypt",
        "Casablanca, Morocco",
        "Lagos, Nigeria",
        "Nairobi, Kenya",
        "Johannesburg, South Africa",
        "Cape Town, South Africa",
        "Accra, Ghana",
        "Addis Ababa, Ethiopia",
        "Istanbul, Turkey",
        "Tehran, Iran",
    ],
    "oceania": [
        "Sydney, Australia",
        "Melbourne, Australia",
        "Brisbane, Australia",
        "Perth, Australia",
        "Adelaide, Australia",
        "Auckland, New Zealand",
        "Wellington, New Zealand",
        "Canberra, Australia",
    ],
}

# ISO 3166-1 alpha-2 — empty code = search all countries worldwide
COUNTRIES: list[dict[str, str]] = [
    {"code": "", "name": "Worldwide (All Countries)"},
    {"code": "AF", "name": "Afghanistan"},
    {"code": "AL", "name": "Albania"},
    {"code": "DZ", "name": "Algeria"},
    {"code": "AD", "name": "Andorra"},
    {"code": "AO", "name": "Angola"},
    {"code": "AG", "name": "Antigua and Barbuda"},
    {"code": "AR", "name": "Argentina"},
    {"code": "AM", "name": "Armenia"},
    {"code": "AU", "name": "Australia"},
    {"code": "AT", "name": "Austria"},
    {"code": "AZ", "name": "Azerbaijan"},
    {"code": "BS", "name": "Bahamas"},
    {"code": "BH", "name": "Bahrain"},
    {"code": "BD", "name": "Bangladesh"},
    {"code": "BB", "name": "Barbados"},
    {"code": "BY", "name": "Belarus"},
    {"code": "BE", "name": "Belgium"},
    {"code": "BZ", "name": "Belize"},
    {"code": "BJ", "name": "Benin"},
    {"code": "BT", "name": "Bhutan"},
    {"code": "BO", "name": "Bolivia"},
    {"code": "BA", "name": "Bosnia and Herzegovina"},
    {"code": "BW", "name": "Botswana"},
    {"code": "BR", "name": "Brazil"},
    {"code": "BN", "name": "Brunei"},
    {"code": "BG", "name": "Bulgaria"},
    {"code": "BF", "name": "Burkina Faso"},
    {"code": "BI", "name": "Burundi"},
    {"code": "CV", "name": "Cabo Verde"},
    {"code": "KH", "name": "Cambodia"},
    {"code": "CM", "name": "Cameroon"},
    {"code": "CA", "name": "Canada"},
    {"code": "CF", "name": "Central African Republic"},
    {"code": "TD", "name": "Chad"},
    {"code": "CL", "name": "Chile"},
    {"code": "CN", "name": "China"},
    {"code": "CO", "name": "Colombia"},
    {"code": "KM", "name": "Comoros"},
    {"code": "CG", "name": "Congo"},
    {"code": "CD", "name": "Congo (DRC)"},
    {"code": "CR", "name": "Costa Rica"},
    {"code": "CI", "name": "Côte d'Ivoire"},
    {"code": "HR", "name": "Croatia"},
    {"code": "CU", "name": "Cuba"},
    {"code": "CY", "name": "Cyprus"},
    {"code": "CZ", "name": "Czech Republic"},
    {"code": "DK", "name": "Denmark"},
    {"code": "DJ", "name": "Djibouti"},
    {"code": "DM", "name": "Dominica"},
    {"code": "DO", "name": "Dominican Republic"},
    {"code": "EC", "name": "Ecuador"},
    {"code": "EG", "name": "Egypt"},
    {"code": "SV", "name": "El Salvador"},
    {"code": "GQ", "name": "Equatorial Guinea"},
    {"code": "ER", "name": "Eritrea"},
    {"code": "EE", "name": "Estonia"},
    {"code": "SZ", "name": "Eswatini"},
    {"code": "ET", "name": "Ethiopia"},
    {"code": "FJ", "name": "Fiji"},
    {"code": "FI", "name": "Finland"},
    {"code": "FR", "name": "France"},
    {"code": "GA", "name": "Gabon"},
    {"code": "GM", "name": "Gambia"},
    {"code": "GE", "name": "Georgia"},
    {"code": "DE", "name": "Germany"},
    {"code": "GH", "name": "Ghana"},
    {"code": "GR", "name": "Greece"},
    {"code": "GD", "name": "Grenada"},
    {"code": "GT", "name": "Guatemala"},
    {"code": "GN", "name": "Guinea"},
    {"code": "GW", "name": "Guinea-Bissau"},
    {"code": "GY", "name": "Guyana"},
    {"code": "HT", "name": "Haiti"},
    {"code": "HN", "name": "Honduras"},
    {"code": "HK", "name": "Hong Kong"},
    {"code": "HU", "name": "Hungary"},
    {"code": "IS", "name": "Iceland"},
    {"code": "IN", "name": "India"},
    {"code": "ID", "name": "Indonesia"},
    {"code": "IR", "name": "Iran"},
    {"code": "IQ", "name": "Iraq"},
    {"code": "IE", "name": "Ireland"},
    {"code": "IL", "name": "Israel"},
    {"code": "IT", "name": "Italy"},
    {"code": "JM", "name": "Jamaica"},
    {"code": "JP", "name": "Japan"},
    {"code": "JO", "name": "Jordan"},
    {"code": "KZ", "name": "Kazakhstan"},
    {"code": "KE", "name": "Kenya"},
    {"code": "KI", "name": "Kiribati"},
    {"code": "KW", "name": "Kuwait"},
    {"code": "KG", "name": "Kyrgyzstan"},
    {"code": "LA", "name": "Laos"},
    {"code": "LV", "name": "Latvia"},
    {"code": "LB", "name": "Lebanon"},
    {"code": "LS", "name": "Lesotho"},
    {"code": "LR", "name": "Liberia"},
    {"code": "LY", "name": "Libya"},
    {"code": "LI", "name": "Liechtenstein"},
    {"code": "LT", "name": "Lithuania"},
    {"code": "LU", "name": "Luxembourg"},
    {"code": "MO", "name": "Macau"},
    {"code": "MG", "name": "Madagascar"},
    {"code": "MW", "name": "Malawi"},
    {"code": "MY", "name": "Malaysia"},
    {"code": "MV", "name": "Maldives"},
    {"code": "ML", "name": "Mali"},
    {"code": "MT", "name": "Malta"},
    {"code": "MH", "name": "Marshall Islands"},
    {"code": "MR", "name": "Mauritania"},
    {"code": "MU", "name": "Mauritius"},
    {"code": "MX", "name": "Mexico"},
    {"code": "FM", "name": "Micronesia"},
    {"code": "MD", "name": "Moldova"},
    {"code": "MC", "name": "Monaco"},
    {"code": "MN", "name": "Mongolia"},
    {"code": "ME", "name": "Montenegro"},
    {"code": "MA", "name": "Morocco"},
    {"code": "MZ", "name": "Mozambique"},
    {"code": "MM", "name": "Myanmar"},
    {"code": "NA", "name": "Namibia"},
    {"code": "NR", "name": "Nauru"},
    {"code": "NP", "name": "Nepal"},
    {"code": "NL", "name": "Netherlands"},
    {"code": "NZ", "name": "New Zealand"},
    {"code": "NI", "name": "Nicaragua"},
    {"code": "NE", "name": "Niger"},
    {"code": "NG", "name": "Nigeria"},
    {"code": "KP", "name": "North Korea"},
    {"code": "MK", "name": "North Macedonia"},
    {"code": "NO", "name": "Norway"},
    {"code": "OM", "name": "Oman"},
    {"code": "PK", "name": "Pakistan"},
    {"code": "PW", "name": "Palau"},
    {"code": "PS", "name": "Palestine"},
    {"code": "PA", "name": "Panama"},
    {"code": "PG", "name": "Papua New Guinea"},
    {"code": "PY", "name": "Paraguay"},
    {"code": "PE", "name": "Peru"},
    {"code": "PH", "name": "Philippines"},
    {"code": "PL", "name": "Poland"},
    {"code": "PT", "name": "Portugal"},
    {"code": "QA", "name": "Qatar"},
    {"code": "RO", "name": "Romania"},
    {"code": "RU", "name": "Russia"},
    {"code": "RW", "name": "Rwanda"},
    {"code": "KN", "name": "Saint Kitts and Nevis"},
    {"code": "LC", "name": "Saint Lucia"},
    {"code": "VC", "name": "Saint Vincent and the Grenadines"},
    {"code": "WS", "name": "Samoa"},
    {"code": "SM", "name": "San Marino"},
    {"code": "ST", "name": "São Tomé and Príncipe"},
    {"code": "SA", "name": "Saudi Arabia"},
    {"code": "SN", "name": "Senegal"},
    {"code": "RS", "name": "Serbia"},
    {"code": "SC", "name": "Seychelles"},
    {"code": "SL", "name": "Sierra Leone"},
    {"code": "SG", "name": "Singapore"},
    {"code": "SK", "name": "Slovakia"},
    {"code": "SI", "name": "Slovenia"},
    {"code": "SB", "name": "Solomon Islands"},
    {"code": "SO", "name": "Somalia"},
    {"code": "ZA", "name": "South Africa"},
    {"code": "KR", "name": "South Korea"},
    {"code": "SS", "name": "South Sudan"},
    {"code": "ES", "name": "Spain"},
    {"code": "LK", "name": "Sri Lanka"},
    {"code": "SD", "name": "Sudan"},
    {"code": "SR", "name": "Suriname"},
    {"code": "SE", "name": "Sweden"},
    {"code": "CH", "name": "Switzerland"},
    {"code": "SY", "name": "Syria"},
    {"code": "TW", "name": "Taiwan"},
    {"code": "TJ", "name": "Tajikistan"},
    {"code": "TZ", "name": "Tanzania"},
    {"code": "TH", "name": "Thailand"},
    {"code": "TL", "name": "Timor-Leste"},
    {"code": "TG", "name": "Togo"},
    {"code": "TO", "name": "Tonga"},
    {"code": "TT", "name": "Trinidad and Tobago"},
    {"code": "TN", "name": "Tunisia"},
    {"code": "TR", "name": "Turkey"},
    {"code": "TM", "name": "Turkmenistan"},
    {"code": "TV", "name": "Tuvalu"},
    {"code": "UG", "name": "Uganda"},
    {"code": "UA", "name": "Ukraine"},
    {"code": "AE", "name": "United Arab Emirates"},
    {"code": "GB", "name": "United Kingdom"},
    {"code": "US", "name": "United States"},
    {"code": "UY", "name": "Uruguay"},
    {"code": "UZ", "name": "Uzbekistan"},
    {"code": "VU", "name": "Vanuatu"},
    {"code": "VA", "name": "Vatican City"},
    {"code": "VE", "name": "Venezuela"},
    {"code": "VN", "name": "Vietnam"},
    {"code": "YE", "name": "Yemen"},
    {"code": "ZM", "name": "Zambia"},
    {"code": "ZW", "name": "Zimbabwe"},
]

COUNTRY_NAME_BY_CODE = {item["code"]: item["name"] for item in COUNTRIES if item["code"]}
